import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import dynamic from "next/dynamic";
import styles from '../styles/Home.module.css'
// import QrReader from "react-qr-reader";
import {useCallback} from "react";

const QrReader = dynamic(() => import('react-qr-reader'), {ssr: false})

const Home: NextPage = () => {

    const handleScan = useCallback((data: string | null) => {
        console.log(data);
    }, [])

    const handleError = useCallback((err: any) => {
        console.log(err);
    }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <QrReader onScan={handleScan} onError={handleError} delay={300} facingMode={'environment'} />
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
